AcademyTOP/Models/Request.cs
namespace AcademyTOP.Models
{
    /// <summary>
    /// Класс заявки
    /// </summary>
    public class Request
    {
        /// <summary>
        /// Ункальный идентификатор заявки
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Фамилия студента
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Фамилия студента
        /// </summary>
        public string Surname { get; set; } = null;
        /// <summary>
        /// Отчество студента
        /// </summary>
        public string Patronymic { get; set; } = null;
        /// <summary>
        /// Номер телефона
        /// </summary>
        public string NumberPhone { get; set; }
        /// <summary>
        /// Номер группы студента
        /// </summary>
        public string NumberGroup {  get; set; }
        /// <summary>
        /// Название курса
        /// </summary>
        public string Block {  get; set; }
        /// <summary>
        /// Дата пропущенного занятия
        /// </summary>
        public DateTime DataMiss {  get; set; }
        /// <summary>
        /// Время, когда студент может придти
        /// </summary>
        public string FreeTime {  get; set; }
        /// <summary>
        /// Справка студента
        /// </summary>
        public IFormFile FormFile { get; set; }
    }
}

AcademyTOP/Controllers/AuthorizationController.cs
using AcademyTOP.DataAccessLayer;
using AcademyTOP.DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Cryptography;
using System.Text;

namespace AcademyTOP.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AuthorizationController(ApplicationDbContext contex)
        {
             _context = contex;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Authorization(Admin admin)
        {
            var request = _context.Database.
            var hashPassword = HashPassword(admin.Password);

            return View();
        }

        public static string HashPassword(string password)
        {
            using (var sha256 = SHA256.Create())
            {
                byte[] hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(hashedBytes);
            }
        }
    }
}

AcademyTOP/Controllers/HomeController.cs
using AcademyTOP.DataAccessLayer;
using AcademyTOP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AcademyTOP.Controllers
{
	public class HomeController : Controller
	{
		private readonly IWebHostEnvironment _hostingEnvironment;
		private readonly ApplicationDbContext _context;

		public HomeController(IWebHostEnvironment hostingEnvironment, ApplicationDbContext context)
		{
			_hostingEnvironment = hostingEnvironment;
			_context = context;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Send(Request req)
		{	
			string[] NameSurnamePatronymic = req.Name.Split(' ');

			try
			{
                req.Surname = NameSurnamePatronymic[0];
                req.Name = NameSurnamePatronymic[1];
                req.Patronymic = NameSurnamePatronymic[2];
            }
			catch (Exception ex)
			{

			}
			

			if (req.FormFile != null && req.FormFile.Length > 0)
			{

				var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "uploads", req.FormFile.FileName);

				using (FileStream stream = new FileStream(filePath, FileMode.Create))
				{
					await req.FormFile.CopyToAsync(stream);
				};
			}

			//Перевод объекта из AcademyTOP.Models.Request в AcademyTOP.DataAccessLayer.Models.Request
			var request = new DataAccessLayer.Models.Request
			{
				Name = req.Name,
				Block = req.Block,
				DataMiss = req.DataMiss,
				FreeTime = req.FreeTime,
				NameFile = req.FormFile?.FileName,
				NumberGroup = req.NumberGroup,
				NumberPhone = req.NumberPhone,
				Patronymic = req.Patronymic,
				Surname = req.Surname,
			};
			//Отслеживание нового объекта
            await _context.Requests.AddAsync(request);

			//Сохранение данных
			await _context.SaveChangesAsync();

			return View();
		}

	}
		

}

AcademyTOP/Views/Authorization/Index.cshtml
<main>
    <form asp-controller="Authorization" asp-action="Authorization" class="form" method="post" enctype="multipart/form-data">
        <div class="element form-group">
            <label for="InputLogin">Логин</label>
            <input name="login" type="text" class="form-control" id="InputLogin" placeholder="Введите логин" required>
        </div>

        <div class="element form-group">
            <label for="InputPassword">Пароль</label>
            <input name="password" type="password" class="form-control" id="InputPassword" placeholder="Введите пароль" required>
        </div>

        <div class="element button">
            <button type="submit" class="btn btn-primary mb-2">Отправить</button>
        </div>


    </form>

</main>

AcademyTOP/Views/Home/Index.cshtml
<main>
    <form asp-controller="Home" asp-action="Send" class="form" method="post" enctype="multipart/form-data">
        <div class="element form-group">
            <label for="InputName">ФИО ребенка</label>
            <input name="name" type="text" class="form-control" id="InputName" placeholder="Введите ФИО ребенка" required>
            <small class="form-text text-muted">Например: Ардинцев Максим Александрович</small>
        </div>

        <div class="element form-group">
            <label for="InputNumber">Номер телефона</label>
            <input name="numberPhone" type="text" class="form-control" id="InputNumber" placeholder="Введите номер телефона" required>
            <small class="form-text text-muted">Например: 89274743480</small>
        </div>

        <div class="element form-group">
            <label for="InputGroup">Группа</label>
            <input name="numberGroup" type="text" class="form-control" id="InputGropup" placeholder="Введите название группы" required>
            <small class="form-text text-muted">Например: В3213</small>
        </div>

        <div class="element form-group">
            <label for="InputBlock">Блок</label>
            <select name="block" class="form-control" id="InputList">
                <option disabled selected>Выберите блок</option>
                <option>Construct 3</option>
                <option>Kodu</option>
                <option>Python</option>
                <option>C#</option>
                <option>C++</option>
            </select>
        </div>

        @* <div class="element form-group">
            <label for="InputTheme">Тема</label>
            <input name="theme" type="text" class="form-control" id="InputTheme" placeholder="Введите название пропущенной темы или номер урока" required>
            <small class="form-text text-muted">Например: Введение в SketchUp</small>
        </div>
 *@
        <div class="element form-group">
            <label for="InputDataLess">Когда было пропущено занятие?</label>
            <input name="dataMiss" type="text" class="form-control" id="InputDataLess" placeholder="Введите даты занятий" required>
            <small class="form-text text-muted">Например: 20.03.24</small>
        </div>

        <div class="element form-group">
            <label for="InputData">Когда Вы сможете прийти на консультацию?</label>
            <input name="freeTime" type="text" class="form-control" id="InputData" placeholder="Введите свободные часы" required>
            <small class="form-text text-muted">Например: 20.03.24 с 10:00 до 13:00, 21.03.24 с 15:00 до 18:00</small>
        </div>

        <div class="element form-group">

            <label for="FormControlFile">Прикрепите справку из больницы(фото):</label><br><br>
            <input name="formFile" type="file" class="form-control-file" id="file" required>
        </div>



        <div class="element button">
            <button type="submit" class="btn btn-primary mb-2">Отправить</button>
        </div>


    </form>

</main>

AcademyTOP/Views/Home/Send.cshtml
<main>
    <form asp-controller="Home" asp-action="Index" method="get" class="form">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="alert alert-success text-center" role="alert">
                        Данные успешно отправлены!
                    </div>
                </div>
            </div>
       
            <div class="button">
                <button class="btn btn-primary mb-2" type="submit">Главная страница</button>
            </div>
        

        </div>
    </form>
</main>

AcademyTOP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AcademyTOP</title>
    <link rel="icon" href="~/images/icon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class="head">
            <div class="holder-logo">
                <span>
                    <b>AcademyTOP</b>
                    <img src="~/images/logo.png" alt="Логотип" width="50px">
                </span>
            </div>
            
        </div>
        

    </header>
    <form class="holder-button" asp-controller="Authorization" asp-action="Index">
        <button class="btn btn-light mb-2" id="login" >Войти</button>
    </form>
    @RenderBody()

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>